from constants.itemnames import *

PRETTY_ITEM_NAMES = {
    (PROGRESSIVE_SWORD, 1): PRACTICE_SWORD,
    (PROGRESSIVE_SWORD, 2): GODDESS_SWORD,
    (PROGRESSIVE_SWORD, 3): GODDESS_LONGSWORD,
    (PROGRESSIVE_SWORD, 4): GODDESS_WHITE_SWORD,
    (PROGRESSIVE_SWORD, 5): MASTER_SWORD,
    (PROGRESSIVE_SWORD, 6): TRUE_MASTER_SWORD,
    (PROGRESSIVE_BEETLE, 1): BEETLE,
    (PROGRESSIVE_BEETLE, 2): HOOK_BEETLE,
    (PROGRESSIVE_BEETLE, 3): QUICK_BEETLE,
    (PROGRESSIVE_BEETLE, 4): TOUGH_BEETLE,
    (PROGRESSIVE_BOW, 1): BOW,
    (PROGRESSIVE_BOW, 2): IRON_BOW,
    (PROGRESSIVE_BOW, 3): SACRED_BOW,
    (PROGRESSIVE_SLINGSHOT, 1): SLINGSHOT,
    (PROGRESSIVE_SLINGSHOT, 2): SCATTERSHOT,
    (PROGRESSIVE_BUG_NET, 1): BUG_NET,
    (PROGRESSIVE_BUG_NET, 2): BIG_BUG_NET,
    (PROGRESSIVE_MITTS, 1): DIGGING_MITTS,
    (PROGRESSIVE_MITTS, 2): MOGMA_MITTS,
    (SOTH_PART, 4): SONG_OF_THE_HERO,
}
